### ISSUE TITLE
Fails to list available manage.py subcommands

### ISSUE THREAD

**Issue by cachitas** [neutron-sync/pdm-django#1]
The provided shortcut `pdm manage` fails to replicate default behavior. See example below.

```sh
$ pdm manage
No command is given, default to the Python REPL.
Unknown command: 'python'
Type 'manage.py help' for usage.
```

```sh
$ pdm run python manage.py
Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[contenttypes]
    remove_stale_contenttypes

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver
```

I trimmed the above output. You get the idea.

**Comment by pizzapanther** [comment]
I noticed this earlier but was wondering if anyone else would notice. 😃

I essentially hijacked `pdm run`. So when you run a bare manage command, you are running `pdm run` bare.

I can probably fix it shortly. Thanks for the report.

**Comment by pizzapanther** [comment]
ok I just uploaded version 0.3.0 for a fix: https://pypi.org/project/pdm-django/

There are still some CLI option conflicts between the pdm command and django. However, it is only one that I can find: `pdm manage --help`. `pdm manage` should work now. I noted the conflicts here: https://github.com/neutron-sync/pdm-django#cli-option-conflicts
